spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/locationdb
    pool-size: 30
    platform: postgres
    initialization-mode: always
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql